name: Test commit
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Setup snap
        run: |
          cat <<- 'EOF' > /usr/bin/systemctl
            #!/bin/bash
            
            # First parameter should be start or stop
            # Second parameter will be the name of a unit file
            
            if [ $# -lt 2 ]
            then 
              echo "usage: $0 start unit-file"
              exit 0
            fi
            
            if [ $1 == "start" ]
            then
              what=$(grep What /etc/systemd/system/"$2" | cut -f 2 -d '=')
              where=$(grep Where /etc/systemd/system/"$2" | cut -f 2 -d '=')
              mkdir -p "$where"
              mount $what $where
              exit 0
            fi
            
            if [ $1 == "stop" ]
            then
              where=$(grep Where /etc/systemd/system/"$2" | cut -f 2 -d '=')
              umount $where
              exit 0
            fi
          EOF
          apt-get update && apt-get install -y snapd
          snap version
          systemctl enable --now snapd.socket
          systemctl start snapd
          snap install core
      - name: Install dependencies
        run: |
          snap install zig --classic --edge
          zig version
      - name: Run tests
        run: zig build test
