name: Test commit
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          snap install zig --classic --edge
          zig version
      - name: Run tests
        run: zig build test
