name: Test commit
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/mlugg/setup-zig@v2
      - name: Run tests
        run: zig build test --summary all
